### ISSUE TITLE
Reports - Ticket counts report Total Open not adding up (should be Total Allocation - Total Sold - Total Held)

### ISSUE THREAD

**Issue by zmelamed** [big-neon/bn-web#1012]
<img width="941" alt="banners_and_alerts_and_big_neon___concert_and_live_event_ticketing" src="https://user-images.githubusercontent.com/456953/51700907-34c46e00-1fde-11e9-9a4e-b99f0979b469.png">

**Comment by Jasonvdb** [comment]
So when I increase the quantity, that value seems to save. Lowering doesn't.
