### ISSUE TITLE
Reporting - Ticket Counts report not showing accurate revenue numbers

### ISSUE THREAD

**Issue by zmelamed** [big-neon/bn-web#1021]
connects to big-neon/bn-web#1012

Ticket counts report on staging and production showing numbers that don't match other reports.
Ticket counts report here shows 0 sold online and 10 comps, and Allocation vs. Open that doesn't add up.
<img width="1440" alt="screenshot_1_28_19__12_26_pm" src="https://user-images.githubusercontent.com/456953/51864336-57b19380-22f8-11e9-9752-42262a8bb369.png">
Event summary report shows 9 sold and no comps...
<img width="1440" alt="big_neon_-_the_new_standard_in_event_ticketing" src="https://user-images.githubusercontent.com/456953/51864361-6bf59080-22f8-11e9-913a-164966e641e0.png">

**Comment by zmelamed** [comment]
@Krakaw @mikethetike @Jasonvdb can you put your heads together and try and dig into these reports to reconcile the ticket count issues... 

Outside of the discrepancy here in tickets sold and comps between the two reports, `Allocation` should always represent the total number of tickets open + total sold + total held + total comps (a ticket can either be open, sold, held, or comp'd--they can't exist in any more than 1 of those buckets at a time in these reports)... "How many of these tickets exist so I know how many people may show up to my event?" is the question total allocation needs to answer.

**Comment by Krakaw** [comment]
@zmelamed If a ticket was in a hold and it gets sold, must it move into "Sold" and out of "Comp"?

**Comment by zmelamed** [comment]
A "comp" in the eyes of the venue on these reports just means a $0 ticket. If a ticket is in a hold and that hold is a hold of compd tickets and it gets claimed by/transferred to/used by someone it would be +1 in the Comp, -1 in the hold. If a ticket costs anything it is considered "Sold", so If I sell from a hold it would be +1 to Sold and -1 to Hold.

**Comment by Krakaw** [comment]
So for these reports, can I combine all unassigned comps AND holds into "Holds" and only the 0 value ones that get used will move into Comps, and the non 0 value ones will move into Sold.

**Comment by zmelamed** [comment]
Yes that sounds correct

**Comment by Krakaw** [comment]
Created event with 10 tickets total.
Created a hold with 2 tickets (at a 50% discount)
Created a comp with 2 tickets
Bought 1 ticket as per normal.
Bought 1 ticket using the COMP code
Bought 1 ticket using the HOLD code
Bought another normal ticket and refunded it.
Bought 1 ticket through the box office.
![screenshot 2019-01-29 at 11 36 52](https://user-images.githubusercontent.com/41575888/51898720-35804a00-23ba-11e9-8ec2-64b6a0350ca9.png)

**Comment by zmelamed** [comment]
Total sold should only be 3, a comp isn't considered "Sold". 

Regardless of whether held inventory is a comp, or discounted, or regular price, until it is transferred or used by a guest it's just a hold... "I'm holding 2 free tickets out of inventory", "I'm holding 2 discounted tix out of inventory", "I'm holding 2 regular price tix out of inventory"... All of those are just Hold = 2...

In this order:
Allocation = 10
Sold Online = 1
Sold BO = 1
Total Sold = 3 (Sold Online + Sold BO)
Comps = 1
Held = 2 
Open = 4
