### ISSUE TITLE
A person should be able to scan a QR code to quickly access an event detail page

### ISSUE THREAD

**Issue by zmelamed** [big-neon/bn-web#105]
child of big-neon/docs#23

**Comment by Jasonvdb** [comment]
@zmelamed I can create a QR code on the web that directs the user to the event detail page. But which page does that QR go on?

**Comment by zmelamed** [comment]
The qr code will be something a venue will eventually be able to print and display outside of an event for people to quickly find the event in the app so to reduce the line of people trying to buy tickets at the door/box office. So the client apps will have a search by qr code option.

**Comment by Jasonvdb** [comment]
Ok thanks. Will make the QR code contain a direct link to the event. If they have the app installed and it'll deep link straight to the view in the big neon mobile app. If it's not installed it'll open the event details page in the phone's web browser.
