### ISSUE TITLE
SEO - Eliminate render-blocking resources

### ISSUE THREAD

**Issue by Jasonvdb** [big-neon/bn-web#1053]
connects to big-neon/bigneon#51
https://developers.google.com/web/tools/lighthouse/audits/blocking-resources

https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fwww.bigneon.com%2F&tab=mobile

**Comment by Jasonvdb** [comment]
Can probably get rid of style.css but I think the main css will still need to block the first paint
![Screenshot 2019-05-20 at 12 14 17](https://user-images.githubusercontent.com/5300488/58014312-dbd29580-7af8-11e9-8f89-bc4ef2b66595.png)

**Comment by Anziskavds** [comment]
Reviewed and work as expected
