### ISSUE TITLE
Globee - Purchase Tickets button enabled without payment type selected... after bailing on globee payment still sends confirmation email

### ISSUE THREAD

**Issue by zmelamed** [big-neon/bn-web#1072]
Add ticket for MCC to cart
Select Globee as payment method
Click Purchase Tickets
Go back to checkout page after being redirected--no payment method selected
Click Purchase Tickets
https://cl.ly/1ea13f8f0570

**Comment by Jasonvdb** [comment]
Disabling the button until the user selects payment method is a quick UI fix but the confirmation of bought tickets while not having paid is a bn-api issue for sure.
