### ISSUE TITLE
Mobile Web UX - After clicking a link from an email invite you can't scroll the app until you refresh -- blocks account creation

### ISSUE THREAD

**Issue by zmelamed** [big-neon/bn-web#1111]

**Comment by Jasonvdb** [comment]
@zmelamed is this on iOS that you noticed this?

**Comment by zmelamed** [comment]
Yes iOS

**Comment by Jasonvdb** [comment]
There's this obscure bug when it comes to scrolling and overlay dialogs. It's actually a bug in iOS itself: https://bugs.webkit.org/show_bug.cgi?id=153852

I implemented a workaround a little while ago that I've now updated. I'm pretty sure it should be fixed across the app now but let me know if it happens anywhere else.
