### ISSUE TITLE
Transaction Detail Reports - Add search

### ISSUE THREAD

**Issue by zmelamed** [big-neon/bn-web#1207]
connects to big-neon/bigneon#54
org and event level

Should have a search field

Should be able to search by name, email, order number, event name

**Comment by mikethetike** [comment]
API is ready for this one in big-neon/bn-api#1143

**Comment by Anziskavds** [comment]
Tested successful on develop, beta and prod by searching with the first and last name, by only the first name or last name, order numbers, event names email but it tested unsuccessful by trying to search with the last name and the first name. Should you be able to search with the last and first name? This appear on both web and mobile web. @Tas4tari @shanimal08

**Comment by Anziskavds** [comment]
@Tas4tari Do you know who can answer me on my above question?

**Comment by Anziskavds** [comment]
@harrisonlemon Does the same apply to this issue? No need to search with [Last name] [First name]?

**Comment by Anziskavds** [comment]
Tested successful on Develop, Beta and Prod by searching with 
[First name]
[Last name]
[First name][Last name]
[Email]
[Event name]
[Order #]
