### ISSUE TITLE
Promo code - non-unique promo codes (across events) are not handled correctly by frontend during ticket selection

### ISSUE THREAD

**Issue by philipr-za** [big-neon/bn-web#1332]
If you create two promo codes on different events with the same redemption code on ticket selection the front-end rejects applying the code because its for the wrong event.

**Comment by Jasonvdb** [comment]
@philipr-za when validating the code on the frontend, in this case does the api just return multiple ticket_types belonging to different events?

**Comment by philipr-za** [comment]
I initially thought so but looks like the api is not handling this correctly either. Made an issue to look at it in the api here https://github.com/big-neon/bn-api/issues/1197
