### ISSUE TITLE
Door person: box office guests issues

### ISSUE THREAD

**Issue by Timo614** [big-neon/bn-web#1362]
1. On http://localhost:3000/box-office/guests as a doorperson I see the network tab has an error for the http://localhost:9000/events/693381b0-3eb6-41a6-8fb4-015f44da82c1/codes?type=Access with a 401 response. I looked into it a bit on the API side and it's because the doorperson does not have `CodeRead` access. 

We could add it on the API side if we want to grant that access but it wasn't clear from the page how it was using the API response as I added it locally and saw no change to what was displayed. 

2. The doorperson currently sees an order link but they don't have access to view the user's orders so it leads to an error page.

![Screen Shot 2019-04-16 at 2 08 40 PM](https://user-images.githubusercontent.com/1319304/56233978-4b64e900-6052-11e9-8822-840885176aca.png)

**Comment by philipr-za** [comment]
Good find! Turns out I only ever tested this as a super user 🤦‍♂️ . This is an issue for the Box Office in general. I am going to do a quick PR to sort out the access right for box office and door person.
