### ISSUE TITLE
Fan list paging doesn't work as expected

### ISSUE THREAD

**Issue by mikethetike** [big-neon/bn-web#1392]
* Previous is not enabled
* Cannot click on pages great than 6:
![image](https://user-images.githubusercontent.com/4200336/56953247-5896d300-6b3c-11e9-9eb4-1bf078797c99.png)
* When on page 6 (see diagram) page 7 should appear as a button

**Comment by danielhalupka** [comment]
I fixed this for Fan list, but then discovered that it's actually an global issue with pagination. You can check it on admin/reports/transaction, by lowering the limit to 1. Fixing it

**Comment by danielhalupka** [comment]
PR was created.

**Comment by Anziskavds** [comment]
Reviewed and working as expected

**Comment by Anziskavds** [comment]
Tested with Keith yesterday on Prod and it is working as expected.
@Krakaw
