### ISSUE TITLE
Reports - Various reports reflect incorrect sales data

### ISSUE THREAD

**Issue by Timo614** [big-neon/bn-web#1417]
connected to big-neon/bigneon#139

- Event Summary Audit (screencap https://cl.ly/42ba1b99723b)

1. 'Price' column reflects full face value of ticket when a discount has been applied.

2. Total Sales column is all $0 regardless of sales data

https://github.com/big-neon/bigneon/issues/139#issuecomment-498345069

'Face' refers to the customer-facing ticket price, as opposed to the set base ticket price or the net ticket price*. Reports will have different criteria, depending on accessibility (which users can access the reports) and how detailed the report is.

The Event Summary Audit is accessible by org-level users only, but could be shared with 3rd parties. There are 2 issues occurring here:

1. The 'Total' column does not calculate. All 'totals' are $0 regardless of sales data. This is an incorrect calculation.
2. The word 'Face' is misrepresented. The face value is what the consumer pays, rather than the base price of the ticket. The Audit here should represent the face value of the ticket. Otherwise we would not need to breakout a separate line item.

*Net ticket price = base ticket price less inclusive fees

**Comment by Timo614** [comment]
I have a branch ready if it ends up being we do want to use the face value here: https://github.com/big-neon/bn-web/compare/master...Timo614:fix-total-face-calculation?expand=1 will wait to push it up as a PR until I hear back though from the parent issue as we may end up wanting to switch the logic to show price and total price instead.

**Comment by Timo614** [comment]
@zmelamed just a quick ping re:
https://github.com/big-neon/bigneon/issues/139#issuecomment-490167709

The values here are off still for this aspect of the main ticket was just waiting there on pushing this PR up (have a branch linked above) until we confirmed what behavior we wanted there.

**Comment by Tas4tari** [comment]
@zmelamed Please can you confirm the above.

**Comment by zmelamed** [comment]
@harrisonlemon can you help provide some guidance here it's related to your ticket big-neon/bigneon#139

**Comment by Timo614** [comment]
Updated to include comments from the parent issue re: this remaining item.

**Comment by harrisonlemon** [comment]
@zmelamed @Timo614 'Face' refers to the customer-facing ticket price, as opposed to the set base ticket price or the net ticket price*. Reports will have different criteria, depending on accessibility (which users can access the reports) and how detailed the report is.

The Event Summary Audit is accessible by org-level users only, but could be shared with 3rd parties. There are 2 issues occurring here:

1. The 'Total' column does not calculate. All 'totals' are $0 regardless of sales data. This is an incorrect calculation.

2. The word 'Face' is misrepresented. The face value is what the consumer pays, rather than the base price of the ticket. The Audit here should represent the face value of the ticket. Otherwise we would not need to breakout a separate line item.

*Net ticket price = base ticket price less inclusive fees

**Comment by Timo614** [comment]
Gotcha I think I understand now. So the face is the full price they pay ticket fee inclusive (not order fee since it's spread across multiple ticket purchases in the same order?).

So if I have a $30 ticket with 0.10 total ticket fees and 1.00 order fee the value for the price should be $30.10 and the total should be the quantity sold multiplied by that?

So an example going through what I mentioned above would lead to these results?
![Screen Shot 2019-06-04 at 1 42 06 PM](https://user-images.githubusercontent.com/1319304/58901449-378f4800-86cf-11e9-931e-379ff10c9786.png)
![Screen Shot 2019-06-04 at 1 42 18 PM](https://user-images.githubusercontent.com/1319304/58901450-378f4800-86cf-11e9-86ec-f0ac7d8e19e3.png)
![Screen Shot 2019-06-04 at 1 43 40 PM](https://user-images.githubusercontent.com/1319304/58901452-378f4800-86cf-11e9-93d0-f347375a673e.png)

And for the various discounts, comps etc:
![Screen Shot 2019-06-04 at 1 41 42 PM](https://user-images.githubusercontent.com/1319304/58901448-378f4800-86cf-11e9-9819-716f7a0a5306.png)

If that's the case I have PRs I can push up for api and web changes. Just confirming since these concepts are a bit new to me.

**Comment by Timo614** [comment]
I pushed up two PRs which should address this assuming my understanding of face price is correct. Let me know and I'll remove that tag so it can be merged in or make any adjustments if I misunderstood the explanation above.

**Comment by Timo614** [comment]
@harrisonlemon can you confirm the above please.

**Comment by Timo614** [comment]
Talked with Harrison via chat. Given the fees are not currently inclusive they shouldn't be included in the face value so the only changes that needed to be made here were in bn-api.

Not sure if we want to close this issue or keep it around until the API side has merged in just as a precaution:
https://github.com/big-neon/bn-api/issues/1310

I tested it locally and everything looks good post changes.

![Screen Shot 2019-06-10 at 12 01 33 PM](https://user-images.githubusercontent.com/1319304/59209732-081e8680-8b7a-11e9-924e-7ba5029e3de5.png)

**Comment by nine-tari** [comment]
Keeping open for us to verify it's set but the bn-api changes which fixed this are merged.

**Comment by Anziskavds** [comment]
Tested on Beta and looks like the data is correct

**Comment by Anziskavds** [comment]
Tested on Prod and looks like the calculations are correct.
