### ISSUE TITLE
Transfers - A user should be able to cancel a ticket transfer they created until the transfer is accepted

### ISSUE THREAD

**Issue by Timo614** [big-neon/bn-web#1418]
connected to big-neon/bigneon#145

Blocked by: big-neon/bn-api/issues/1260

Context: If a user creates a ticket transfer request and that ticket has not yet been accepted/added to another users wallet, the transferrer should be able to cancel the transfer request

- When a user has a ticket in a transfer state they should be presented with an action button to `Cancel Transfer`.
- When a the `Cancel Transfer` button is clicked, the user should see a confirmation dialog `Are you sure you want to cancel this ticket transfer?`
- If the user clicks `Yes, cancel transfer`:
  - The transfer should be expired

**Comment by nine-tari** [comment]
Should we remove the blocked here? The associated issue had its PR merged. https://github.com/big-neon/bn-api/pull/1263 

Was set as blocked initially as it was waiting on the API but it should be set now.

**Comment by Krakaw** [comment]
I set this issue as the blocker because we need the designs before we can effectively test the API side (from an end to end QA perspective)

**Comment by Tas4tari** [comment]
@zmelamed Hi, please can you provide a timeline if possible with regards to the designs required for this

**Comment by zmelamed** [comment]
I see some work has already begun, please see #181. 

Ticket transfer interfaces are in progress here: 
Mobile: https://share.goabstract.com/6e52c96b-414a-4687-aa80-ce024fb0c8a1
Desktop: https://share.goabstract.com/0832d3a4-e188-4405-855b-6807cab26704

While we haven't yet focused on the My Events view on the web specifically the cancel link from the email into the web cancellation flow can begin and the Cancel button on transfer in progress tickets in the mobile app can move forward.

**Comment by Anziskavds** [comment]
Tested on Prod and works as expected.
