### ISSUE TITLE
An Organization should be able to list events on their website hosted outside of the platform (api/widget)

### ISSUE THREAD

**Issue by zmelamed** [big-neon/bn-web#144]
child of big-neon/docs#18

**Comment by Jasonvdb** [comment]
@zmelamed I added a widget builder that generates code for an iframe someone can use to embed the event details on their site. 

I don't have designs for what the widgets should look like yet so I created a basic one. But I implemented it in such a way where we can simply add more templates as we need and the org owner can select which type they want to create and display on their site.

![screenshot 2018-10-12 at 10 27 51](https://user-images.githubusercontent.com/5300488/46857630-a0a51100-ce09-11e8-8748-0ea612b82187.png)
