### ISSUE TITLE
SEO - Event data objects per this spec should be embedded on the page: 

### ISSUE THREAD

**Issue by Jasonvdb** [big-neon/bn-web#1451]
A single Event data objects per this spec should be embedded on the page: https://developers.google.com/search/docs/data-types/event
- This must include the offers schema with all active ticket types
- This must include the `"performer": { "@type": "MusicGroup" ... }`

```
<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "BreadcrumbList",
  "itemListElement": [{
    "@type": "ListItem",
    "position": 1,
    "name": "Concert Tickets",
    "item": "https://www.bigneon.com"
  },{
    "@type": "ListItem",
    "position": 2,
    "name": "[Event Name]",
    "item": "https://www.bigneon.com/[event-name-hyphonated]/event/[event-id]/"
  }]
}
</script>
```

**Comment by Jasonvdb** [comment]
@zmelamed where did you get the above snippet of code? What I see in the docs looks a little different. I'm working from these: https://developers.google.com/search/docs/data-types/event#datatypes and I'll use that google structured data tool to test.

**Comment by zmelamed** [comment]
@Jasonvdb that snippet is the breadcrumb data-type object snippet. If you goto TF or EB event page and view source you can see their event object snippets there, but you can follow the instructions per the google docs and we'll be most of the way there.

**Comment by Jasonvdb** [comment]
Ok thanks I see now, so I'm adding both breadcrumb and event data:
https://developers.google.com/search/docs/data-types/breadcrumb
and 
https://developers.google.com/search/docs/data-types/event

**Comment by Jasonvdb** [comment]
![Screenshot 2019-05-29 at 09 43 25](https://user-images.githubusercontent.com/5300488/58538836-43be6580-81f6-11e9-8fe9-c10a4c5f8e0a.png)

**Comment by Anziskavds** [comment]
Reviewed and work as expected
