### ISSUE TITLE
CSV export includes row with "data:text/csv;charset=utf-8," 

### ISSUE THREAD

**Issue by Timo614** [big-neon/bn-web#1468]
Related to #1441 -- I missed it when testing as I was using dummy data to generate my CSV given it needed a large dataset. The line that exists now was used by the old CSV format to help create the link but it's not needed / leads to it getting included in the output if it's there with the blob approach.

**Comment by Anziskavds** [comment]
Reviewed and working as expected

**Comment by Anziskavds** [comment]
Tested the export of a CSV report with large data with Keith on Prod and exported the report successfully. @Krakaw
