### ISSUE TITLE
Split up updating of events into tabs (wizard)

### ISSUE THREAD

**Issue by Jasonvdb** [big-neon/bn-web#148]
Event details, artists, ticket allocations all on separate tabs.

**Comment by Jasonvdb** [comment]
@zmelamed @Krakaw  do you guys think it would be better to split up the screen for adding an event into different tabs so it'll work more like a wizard instead of one very long form.

The form (https://zpl.io/aXzJl8E) will get especially long when adding multiple artists and multiple tickets with price points. 

Will also make it much simpler for an Org member to just edit one section quickly.

We can break it down into 
- Event details (name, dates, age limit, photos etc)
- Artists (find artist by name, add set time)
- Ticket allocations (name, dates, capacity, price points etc)

**Comment by zmelamed** [comment]
We’ll want to have artist selection first, the event title in many ticketing platforms is auto generated from the headlining artists name, same with the description which is something we should implement. 

So the order matters in that regard. 

I think splitting event details+artists, and then ticketing into a separate tab makes good sense.

**Comment by Jasonvdb** [comment]
Ok great will split them up with then with artists first. It's a bit tricky with the API needing event details first and then adding artists in a separate call but think we can work something out.
