### ISSUE TITLE
Event Dashboard - When a event ended information on graph should only show up to the last sale date

### ISSUE THREAD

**Issue by Anziskavds** [big-neon/bn-web#1482]
Steps to reproduce:

-When a event has ended the graph must only show up to the last sales date and no further

![Image Pasted at 2019-5-24 13-37.png](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/358dff8c-6b30-4f03-843f-bfd59ecd4e25)

**Comment by Krakaw** [comment]
Issue moved to [big-neon/bn-api #1325](https://github.com/big-neon/bn-api/issues/1325) via [**ZenHub**](https://www.zenhub.com/)
