### ISSUE TITLE
Fan Profile Management: Fan Profile Redesign: User Information

### ISSUE THREAD

**Issue by Tas4tari** [big-neon/bn-web#1503]
- [x] Users Name
- [x] Users Email
- [x] ~ Location (if available) ~ **As per Natasha's comment below, she'll create another issue for the location**

**Comment by shanimal08** [comment]
Done but can't be merged as the rest of the page is still in progress

**Comment by Anziskavds** [comment]
Tested successful on Develop. I couldn't test if the location shows because my location is not available.

**Comment by Anziskavds** [comment]
Tested Beta on web and mobile web. But I have noticed that non of the fans shows the fans location. Shannon said there is also no location added to the API, is this something we need to change before this release? @Tas4tari @shanimal08

**Comment by Tas4tari** [comment]
@Anziskavds  @shanimal08 The design does have a location displayed within it so we need to ensure that the displaying of the location works, @shanimal08 how much work would this constitute?

**Comment by shanimal08** [comment]
@Tas4tari if it were just me displaying the location, it'd be 2 mins. BUT it's not coming from the API.. and also I just checked, when you sign up/register.. there isn't anywhere you even set your location. So I'm not sure it's a thing 😅

**Comment by Tas4tari** [comment]
@Anziskavds please remove the location from testing for the interim. I will create a separate issue for this

**Comment by Anziskavds** [comment]
User Name and User Email tested successful on Beta on web and mobile web.

**Comment by Anziskavds** [comment]
Tested successful on Prod for web and mobile web.
