### ISSUE TITLE
Fan Profile Management: Fan Profile Redesign: Event Activity: Current Functionality

### ISSUE THREAD

**Issue by Tas4tari** [big-neon/bn-web#1504]
Organised by Events filtered by Upcoming and Past (Default: Upcoming)

**Comment by Anziskavds** [comment]
Tested on develop and it is not working as expected. 
https://cl.ly/005803427a53

**Comment by Anziskavds** [comment]
Tested successful on develop.

**Comment by Anziskavds** [comment]
Tested successful on Beta for web and mobile web.

**Comment by Anziskavds** [comment]
Tested successful on Prod for web and mobile web.
