### ISSUE TITLE
Fan Profile Management: Redesign: Event Activity Summary

### ISSUE THREAD

**Issue by Tas4tari** [big-neon/bn-web#1505]
Each Event Summary Card should contain the following:
- [ ] Event Name
- [ ] Event Venue
  - Name, City, State
- [ ] Event Date and Time

**Comment by Anziskavds** [comment]
Tested successful on develop

**Comment by Anziskavds** [comment]
Tested successful on Beta on web and mobile web.

**Comment by Anziskavds** [comment]
Tested successful on Prod for web and mobile web.
