### ISSUE TITLE
Fan Profile Management: Redesign: Activity Items: Attendee Checked-in

### ISSUE THREAD

**Issue by Tas4tari** [big-neon/bn-web#1507]
- [ ] [User Name] checked-in to [Event Name] ([# Tickets])
 - [ ]  one activity card per attendee (if they check in multiple tickets to the event there should only be one check in activity and the timestamp should be for the first check-in)
 - [ ]  View should show:
   - Checked-in Tickets
   - Ticket ID (Order #) by [Door Person Name] on [Timestamp]

**Comment by Anziskavds** [comment]
Tested on develop and tested unsuccessful in some fields

Steps to reproduce:

- Attendee Checked-in: [User Name] checked-in to [Event Name] **([# Tickets])**, the # tickets shows **(undefined)** https://cl.ly/311c74159f6e
- Attendee Checked-in expanded view: Ticket ID (Order #) by [Door Person Name] on [Timestamp], instead of **by** it shows **scanned by?** https://cl.ly/90f9101c3590

**Comment by Anziskavds** [comment]
- Tested on Develop.
- Only one activity card per attendee (if they check in multiple tickets to the event there should only be one check in activity and the timestamp should be for the first check-in). There is 4 activity cards for the same attendee who checked in 4 tickets.
https://cl.ly/cfcaea014a45

**Comment by Anziskavds** [comment]
Tested successful on develop for web and mobile web.

**Comment by Anziskavds** [comment]
Tested successful on Beta on web and mobile web.

**Comment by Anziskavds** [comment]
Tested unsuccessful on Prod.

Steps to reproduce:

- The door persons name and the users name is swapped around. 
- In the attached image it should be **Anziska van der Schyff** checked in to [event name] and [Ticket ID / Order #] scanned by Zuzu owner: https://cl.ly/973488a009a8

**Comment by Anziskavds** [comment]
Tested successful on develop but still unsuccessful on Beta.

**Comment by Krakaw** [comment]
Beta and prod updated.

**Comment by Anziskavds** [comment]
Prod tested successful on web and mobile web.
