### ISSUE TITLE
Fan Profile Management: Redesign: Activity Items: Refund created

### ISSUE THREAD

**Issue by Tas4tari** [big-neon/bn-web#1508]
- [ ] Refunder Name] refunded [refund amount] to [User Name]
 - [ ] Expanded View should show:
  - [ ]  Items Refunded
    -  Item Name
    -  Item ID
    -  Item Value
  - [ ]  Reason for refund

**Comment by Anziskavds** [comment]
Tested on develop and tested unsuccessful in some of the fields

Steps to reproduce:

- Refund Created: [Refunder Name] refunded [refund amount] to **[User Name]** (Order #), the **User Name doesn't show.** https://cl.ly/37e6232bb561
- Refund created expanded view should show:
Items Refunded
Item Name
**(Undefined?)** **(Not sure why this shows)**
Item ID
Item Value
Reason for refund
https://cl.ly/0da4e39141db

**Comment by Anziskavds** [comment]
Tested successful on develop

**Comment by Anziskavds** [comment]
Tested successful on Beta on web and mobile web.

**Comment by Anziskavds** [comment]
Tested successful on Prod for web and mobile web.
