### ISSUE TITLE
Adding artists to events should be done via typeahead search

### ISSUE THREAD

**Issue by zmelamed** [big-neon/bn-web#152]
child of big-neon/docs#15
requires big-neon/bn-api-node#84

When an event is created, the artist field should be a typeahead search for the Artist rather than a dropdown, as not all Artists will be present in the system. 
If the artist is not available the event creator can Choose "Create a new artist [Artist Name]" from the typeahead results that appear. 
When the event is saved, the artist should be saved to the artists DB and associated in the artist DB with that organization so that we can restrict the use, and management of that specific artist to that organization. Eventually the System Owner can decide if they want the artist to be globally accessible.

**Comment by Jasonvdb** [comment]
@zmelamed will do the typeahead now. I'll make an issue in bn-api to for an point to do this query but I think for MVP I can load them all in the browser and do the query there as there won't be thousands of artists from the start. Then can optimise once someone has time to do the api changes.

For the 'Create a new artist' option are we going to just insert the artist name and then the org member will have to come back later and complete the rest of the artist fields? Another option would be a modal that pops up after they click 'Create a new artist' with the additional artist fields.

Restricting a new artist to an org might be a separate bn-api issue I'll chat to @mikethetike about. Will that be needed when an org owner creates a new artist at `/admin/artists/create` as well?

**Comment by Jasonvdb** [comment]
Ok great didn't see you created the other issues. Will push the typeahead change just now but I think we should make the restricting of artists to an org a separate issue.

**Comment by Jasonvdb** [comment]
The typeahead artist selecting and creating if it doesn't exist is working and merged ( #153 ) into master. Feel free to reopen if it's not working as expected. We can optimise at a later stage if needed to do additional server calls for searching for artists but right now it shouldn't be a problem to load like 1000 artists into memory and filter in the browser. 

So we can close the issue on bn-api and bn-api-node as well and someone can make a new issue to optimise for performance some time in the future.

Right now we have nothing linking artists to orgs but that's a whole separate issue we'll need to create and discuss as it's mostly bn-api changes.
