### ISSUE TITLE
Add pagination to order management page

### ISSUE THREAD

**Issue by Krakaw** [big-neon/bn-web#1535]
A quick win is to add pagination to order management https://develop.bigneon.com/admin/events/1ca16381-8adf-4015-9f74-e3815c35759b/manage-orders
you can use the box office guest list for the current implementation https://develop.bigneon.com/box-office/guests

**Comment by Tas4tari** [comment]
@shanimal08 What is the progress with regards to this

**Comment by Jasonvdb** [comment]
It was merged in. Although now replaced with the new order management list so it's no longer there.
