### ISSUE TITLE
404 after saving FB Pixel in Settings

### ISSUE THREAD

**Issue by mikethetike** [big-neon/bn-web#1537]
To reproduce:
1. Open studio
2. Click on Marketing (side bar)
3. Go to Analytics tab
3. Add FB pixel
4.  Click Update

Actual result:
![image.png](https://images.zenhubusercontent.com/5ce253ae6eb508477b329abf/1d95f108-968a-4b22-b471-072498356639)

**Comment by Anziskavds** [comment]
Tested on Develop and the Facebook pixel updated successful without an error. Beta is still not working. Beta 1.0.444 and Develop is on 1.0.445, might be because Beta is still on the previous version.

**Comment by Anziskavds** [comment]
Tested Develop and Beta and is working as expected. Facebook pixel updates successfully

**Comment by Anziskavds** [comment]
Tested successful on prod
