### ISSUE TITLE
Fees - Event Level Fees

### ISSUE THREAD

**Issue by Tas4tari** [big-neon/bn-web#1547]
Context: More robust fee capabilities are now a need with All Aboard / Espee and Midway. Minimum org & event-level fee requirements:

1. We require the ability to add an additional fee per ticket type.
2. The amount allowed within the additional fee should be capped at $2.

**Comment by Tas4tari** [comment]
@Jasonvdb design has been added to the epic #187

**Comment by Jasonvdb** [comment]
Thanks @Tas4tari the web part of this is super straight forward, all the work is in the api

**Comment by Anziskavds** [comment]
Tested on Develop and Beta and is working as expected

**Comment by Tas4tari** [comment]
@Jasonvdb Zach has reviewed and posted the following comments, could you please build your changes against these comments:
1. This needs to say "(Max $2)" on the form field
2. If more than the max is entered it should automatically show the error state for that field until the number is removed or the number is changed to less than the max. Error should read "Can not be more than $[Max]"

**Comment by Tas4tari** [comment]
@Anziskavds Please add these checks to your test cases

**Comment by Jasonvdb** [comment]
@Tas4tari @zmelamed so already had this coded in. Which org are you looking at on which environment? We set the max fee on an org level in the DB so it needs to exists there for the label to display it and for the client side validation to happen.
![Screenshot 2019-06-26 at 08.48.11.png](https://images.zenhubusercontent.com/5ce2547f6eb508477b329ac7/8b416ed9-7851-4eb8-89f9-90488160b3d0)

**Comment by Anziskavds** [comment]
@Tas4tari It already is on my test cases

**Comment by Tas4tari** [comment]
@Jasonvdb Please see the following:
The missing part here now is that there should be an onChange validation of that field, so someone doesn't have to click save to find out they've put in a number that's too high

**Comment by Anziskavds** [comment]
Tested Prod on Web and Mobile Web and is working as expected
