### ISSUE TITLE
Update cancel transfer dialog

### ISSUE THREAD

**Issue by Jasonvdb** [big-neon/bn-web#1555]
@Jasonvdb how about:
Heading: `Cancelling Transfer`
Body: `Please confirm that you want to cancel transferring the 3 tickets you sent to samuel.johansson@gmail.com. They will be returned to your Big Neon app.`
![image.png](https://images.zenhubusercontent.com/5c8c16315df6d54b7b125005/dbf69cc9-aff3-4d1b-ac0d-833b995c6cd2)

_Originally posted by @zmelamed in https://github.com/big-neon/bn-api/issues/1306#issuecomment-503897185_

**Comment by Jasonvdb** [comment]
@zmelamed just made this it's own issue so I don't forget. It's a quick update.

**Comment by Anziskavds** [comment]
Tested on develop on web and mobile web. The heading and body is correct, I only found that as per above design it shows a **confirm** button and on develop it shows a **cancel transfer** button. Is this the correct expectation? 
https://cl.ly/7356bebf5e1b

**Comment by Tas4tari** [comment]
@Anziskavds @Jasonvdb  The text should match as per the text on the design. So it should be "Confirm"

**Comment by Anziskavds** [comment]
Prod tested successful on web and mobile web.
