### ISSUE TITLE
Maximum fee does not appear next to the Per Ticket Fee Increase when added while creating a new event

### ISSUE THREAD

**Issue by Anziskavds** [big-neon/bn-web#1569]
Steps to reproduce:

- When a admin creates a new event and would like to add an additional fee to a ticket type it does not show the "Per Ticket Fee Increase" max amount in $ which can be added to the ticket.
- It only shows when a admin wants to edit the event to add the additional fee to the ticket type.

https://cl.ly/d543e2602fcd

**Comment by Jasonvdb** [comment]
Thanks I see the issue, fixing it now

**Comment by Anziskavds** [comment]
@Jasonvdb Thanks

**Comment by Anziskavds** [comment]
Same appears in mobile web

**Comment by Jasonvdb** [comment]
Thanks it's been fixed, will deploy soon

**Comment by Anziskavds** [comment]
Tested Prod on Web and Mobile web and it is appears as expected.
