### ISSUE TITLE
Creating a new event with different ticket type sales dates changes after you clicked pulblish event

### ISSUE THREAD

**Issue by Anziskavds** [big-neon/bn-web#1570]
Steps to reproduce:

- Admin created a new event with 3 different ticket types and different sales start dates.
- Admin created first ticket type (GA 1) with sales start date "Immediately"
- Admin created the second ticket type (GA 2) with sales start date "At a specific time"
- Admin created the third ticket type (GA 3) with sales start date "When sales end for GA2"
- Admin published the event and after the event published successful the ticket sales start date changed.
- GA 2 sales start date changed to "Immediately"
- GA 1 and GA 3 sales start dates remained the same.

https://cl.ly/1c8f629ce498

**Comment by Anziskavds** [comment]
The same issue appear on Mobile Web

**Comment by Anziskavds** [comment]
@Jasonvdb This is still an issue. Retested on Prod.

**Comment by Jasonvdb** [comment]
Setting a date in the past and saving will always show up as `immediately` afterwards. @Anziskavds can we remove the fail label?

**Comment by Anziskavds** [comment]
@Jasonvdb Label removed. I tested this on Mobile web and Web on Prod an both is working as expected.
