### ISSUE TITLE
Add 'Category' to events for website listings

### ISSUE THREAD

**Issue by Tas4tari** [big-neon/bn-web#1583]
Categories include:

Music
Art
Culinary
Comedy
Conference
Sports

Additional categories to be added at a later date as we grow. 

Request per PW/The Midway

**Comment by Anziskavds** [comment]
Tested successful on develop on web and mobile web.
https://cl.ly/5391ffc32b59

**Comment by Anziskavds** [comment]
Tested successful on Beta for web and mobile web.

**Comment by Anziskavds** [comment]
Tested successful on Prod on web and mobile web.
