### ISSUE TITLE
If a ticket has been redeemed, remove the actions from My Events

### ISSUE THREAD

**Issue by Krakaw** [big-neon/bn-web#1589]
In `My Events` if a ticket has been redeemed it still shows the option to `show qr` or `transfer` these should be replace with a greyed out, "Redeemed"

**Comment by Anziskavds** [comment]
Tested successful on develop

**Comment by Anziskavds** [comment]
Tested successful on Beta on web and mobile web.

**Comment by Anziskavds** [comment]
Tested successful on Prod on web and mobile web.
