### ISSUE TITLE
Prevent an event END TIMEs for events from being set before SHOWTIME during Event Build

### ISSUE THREAD

**Issue by Tas4tari** [big-neon/bn-web#1590]
Client was able to build an event with the End TIME set before SHOW TIME.

This only occurs during the initial Event Build and is reproducible
https://cl.ly/718ec25e6dcf <https://cl.ly/718ec25e6dcf>
<https://cl.ly/718ec25e6dcf>View here: https://cl.ly/718ec25e6dcf <https://cl.ly/718ec25e6dcf>

After the event is published you WILL receive an error message if you attempt to update the event. The error message received Here  <https://cl.ly/93062623166b>is  what we would expect to happen
If an event is published with the start time after the end time Customer's will not have the ability to see their tickets in Upcoming events, instead, they see them is past events one the end time is set.

**Comment by Tas4tari** [comment]
@Jasonvdb was this PR approved and can it be sent to the Review/QA pipeline or is ther some outstanding work left to do?

**Comment by Jasonvdb** [comment]
Has been merged, ready to QA thanks. Will be in develop at least, I don't know if we've done a beta deploy

**Comment by Anziskavds** [comment]
This issue is the same as issue# 1385

Tested on Prod and it working as expected.

https://cl.ly/77e0fa4cc00f
