### ISSUE TITLE
Venue - Cannot create new venue - city field blocked

### ISSUE THREAD

**Issue by Tas4tari** [big-neon/bn-web#1597]
Overview: when creating a new venue, user is unable to add city information for certain locales. The missing city field blocks creation of new venue.

Only happens for select addresses. For example, user is not able to successfully save venue details for the address:
361 METROPOLITAN AVE, BROOKLYN, NY, 11211, USA

However, the user is able to save the address:
7411 wild valley dr
Dallas, TX 75231

Steps to reproduce:
1. Create New Venue
2. Enter required venue details
3. Click 'create' to save new venue

Can be reproduced in Beta & Prod

Screengrab: https://cl.ly/cf76241cf91e
Screengrab: https://cl.ly/a651873d7e91

**Comment by Tas4tari** [comment]
@Anziskavds Can you please test this issue

**Comment by Tas4tari** [comment]
@Jasonvdb tested this in Develop, still not working correctly. If I add the venue address to Venue location and select create, it expands the enter address section manually and highlights the missing fields in red

**Comment by Jasonvdb** [comment]
Yes it should do that if the missing fields are required? The issue was once it expanded that the user wasn't able to then edit the fields manually. Is that part working?

**Comment by Tas4tari** [comment]
Tested on develop works as expected. All fields do not automatically update as there was no specific requirement set for the page

**Comment by Anziskavds** [comment]
Tested on Beta and is working as expected

**Comment by Tas4tari** [comment]
Tested in Prod and confirmed by @harrisonlemon
