### ISSUE TITLE
Move facebook pixel API input

### ISSUE THREAD

**Issue by Krakaw** [big-neon/bn-web#1614]
![image.png](https://images.zenhubusercontent.com/5c91ad12b65bca7678bd1e8f/e2b26638-e0fc-452c-82ac-55366c4aeb3f)

**Comment by Tas4tari** [comment]
@Anziskavds This is ready for testing for the release today

**Comment by Anziskavds** [comment]
Tested on Beta and it tested successful.

https://cl.ly/9b463c07f9e6

https://cl.ly/7c72905ffdb5

**Comment by Jasonvdb** [comment]
Wait to close, just have a PR that changes it from saving the pixel for an org to saving it to the specific event

**Comment by Anziskavds** [comment]
@Jasonvdb Thank you, Keith also informed me. Let me know when it is ready to retest.

**Comment by Jasonvdb** [comment]
@Anziskavds sorry I forgot to come back to you on this one, you can test

**Comment by Anziskavds** [comment]
@Jasonvdb Is this on Prod or on Develop?

**Comment by Jasonvdb** [comment]
It'll be on both now

**Comment by Anziskavds** [comment]
Tested on Prod, everything tested successful but I found that Facebook pixel ID added to the event level shows **create** instead of **update?** 
@Jasonvdb @Krakaw @Tas4tari 

https://cl.ly/01a7a6c69e8b

**Comment by Jasonvdb** [comment]
Thanks, small UI thing, made a separate issue for that I'll get to later

**Comment by Anziskavds** [comment]
@Jasonvdb Thank you. I'm closing this issue then.

**Comment by Anziskavds** [comment]
Tested on Prod. 

New issue is added for the Facebook pixel ID added to the event level shows create instead of update? Issue #1637
