### ISSUE TITLE
Event Create: Embedded Media option does not function

### ISSUE THREAD

**Issue by Tas4tari** [big-neon/bn-web#1629]
When creating an event, user is presented with an option to 'Add Embedded Media Link.' Once a link is added & the event is saved, the link does not appear on the EDP or Purchase page for the event.

Screengrab: https://cl.ly/da0bea92b065

**Comment by Tas4tari** [comment]
@Jasonvdb @shanimal08 Can you please have a look

**Comment by Jasonvdb** [comment]
Pretty much this issue: https://github.com/big-neon/bigneon/issues/78
We had designs for saving the embedded media but still waiting for designs of how to display them on the event view page.
