### ISSUE TITLE
Ticket Settings: Unable to set Ticket Type End Date with Calendar

### ISSUE THREAD

**Issue by Tas4tari** [big-neon/bn-web#1630]
Overview: User is able to set ticket type end date by choosing date from the calendar or via manual entry.

What we saw: User is unable to set Ticket Type end date when using the calendar. The calendar defaults to the event date. When user selects a new date, the date does not update; event end date continues to display. The user is able to manually enter the event date. 

NOTE: After a date is manually entered, the user opens the calendar to see event end date selected.

Screengrab: https://cl.ly/e00b7c623713

**Comment by Jasonvdb** [comment]
Fix is in.

@Anziskavds will you test this one carefully and maybe add a test case for it.

Originally I thought I broke this with a recent update but looks like it might have been this way for some time, just went unnoticed

**Comment by Anziskavds** [comment]
Tested on Develop and worked as expected.

**Comment by Anziskavds** [comment]
Tested successful on Beta for web and mobile web.

**Comment by Anziskavds** [comment]
Tested successful on Prod on web and mobile web.
