### ISSUE TITLE
Order view for refunds doesn't display refunded amounts

### ISSUE THREAD

**Issue by Timo614** [big-neon/bn-web#1633]
Original seen via: https://github.com/big-neon/bigneon/issues/221

Noticed 3 issues with the order page:

1. It appears when an order is refunded the order view for the customer and admin (seems to be the same component) doesn't reflect the refunded amounts.
2. The fee is also shown as the wrong amount pre-refund in the totals.
3. The discount isn't always displayed directly under the order item it belongs to (it did for the first screenshot but after the refund it appears to be under the quantity 3)

Order view prior to refund (it's correct):
![Screen Shot 2019-07-22 at 1 21 27 PM](https://user-images.githubusercontent.com/1319304/61652408-dd9a1000-ac85-11e9-9a7f-24357657ba18.png)

Trigger refund:
![Screen Shot 2019-07-22 at 1 21 48 PM](https://user-images.githubusercontent.com/1319304/61652409-dd9a1000-ac85-11e9-807d-be2aad8bd719.png)
![Screen Shot 2019-07-22 at 1 21 56 PM](https://user-images.githubusercontent.com/1319304/61652410-dd9a1000-ac85-11e9-8772-ef25fd9339e9.png)

Order view after refund (note $0.20 has been refunded for the fee as well so should be $1.30 now):
![Screen Shot 2019-07-22 at 1 28 17 PM](https://user-images.githubusercontent.com/1319304/61652412-dd9a1000-ac85-11e9-9ac9-d8a1577965fe.png)

**Comment by Jasonvdb** [comment]
@Timo614 new order management components are coming in still, these ones you're looking at won't be used by admin's  anymore https://github.com/big-neon/bn-web/pull/1625

**Comment by Timo614** [comment]
Sounds good, will close this out.
