### ISSUE TITLE
Organization fans list likely should use new field for date added / ordering

### ISSUE THREAD

**Issue by Timo614** [big-neon/bn-web#1635]
Relates to: https://github.com/big-neon/bigneon/issues/221
Blocked by (until merged): https://github.com/big-neon/bn-api/pull/1415

In the pull request https://github.com/big-neon/bn-api/pull/1415 two new fields were added to the fans response:
- first_interaction_time
- last_interaction_time

They were also added to the sort logic to allow for sorting by those fields:
For example (it defaults to desc without specifying): http://localhost:9000/organizations/47be48c0-8490-45bf-92af-a401c2e032d8/fans?page=0&limit=3&sort=LastInteracted

Right now the page orders by last order date:
![Screen Shot 2019-07-22 at 1 55 24 PM](https://user-images.githubusercontent.com/1319304/61653577-9cefc600-ac88-11e9-9e61-ace8891d3210.png)

This has the effect of putting any transferred users at the top. The LastInteracted sort method may be a better call as it'll reflect fans with the latest changes (new transfer, order, event interest, etc.). It also appears as though the page is using the creation date for the user to determine the "Date added". It may be more accurate to use the `first_interaction_time` value there so if a user has been part of the system just new to that organization they won't suddenly pop in with a really old date there.

This can be closed if we don't think there's value just figured with it ordering by their last order it may be troublesome as more events are added with transfer only users.

**Comment by Anziskavds** [comment]
Tested successful on develop, beta and prod on web but tested unsuccessful on mobile web.
Admin is unable to scroll to the right to few the information on the right of the page.

**Comment by Tas4tari** [comment]
@Anziskavds We have refactored the Fan list on mobile as it was not working correctly with all the information that was being displayed. We have removed this information in the interim and will request a design for the Fans list for mobile. Once we have received this, we will enhance this

**Comment by Anziskavds** [comment]
@Tas4tari Thank you.

Tested successful on develop, beta and prod on web.
