### ISSUE TITLE
Redeemed My Events tickets should not have any options

### ISSUE THREAD

**Issue by Krakaw** [big-neon/bn-web#1638]
Remove the `Show QR` and `Transfer` if a ticket is already redeemed. Show a greyed out `Redeemed`

![image.png](https://images.zenhubusercontent.com/5c91ad12b65bca7678bd1e8f/6e027b51-7925-4b0b-80fc-b075d4b13950)

**Comment by Anziskavds** [comment]
Tested successful on develop

**Comment by Anziskavds** [comment]
Tested successful on Beta for web and mobile web.

**Comment by Anziskavds** [comment]
Tested successful on Prod on web and mobile web.

**Comment by Anziskavds** [comment]
Tested successful on Prod on web and mobile web.
