### ISSUE TITLE
When triggering a custom push notification both send buttons are disabled

### ISSUE THREAD

**Issue by Krakaw** [big-neon/bn-web#1644]
![image.png](https://images.zenhubusercontent.com/5c91ad12b65bca7678bd1e8f/e17c559a-267a-4d65-a527-3d9940551fcf)

**Comment by shanimal08** [comment]
@Krakaw just want to make sure - what status should I be checking against for the Notification triggered check?

**Comment by Anziskavds** [comment]
Tested on develop and I tested by sending a custom push notification and a last call notification and only after I send the last call notification the last call notification button was disabled. Is this the correct expectation? https://cl.ly/b62c50769795

**Comment by shanimal08** [comment]
Yes, the last call notification can only be sent once, so it'll be disabled after you send it.. but the custom notification can be anything and can be sent as many times as you like.

**Comment by Anziskavds** [comment]
Tested successful on develop.

**Comment by Anziskavds** [comment]
Tested successful on Beta on web and mobile web.

**Comment by Anziskavds** [comment]
Tested successful on Prod on web and mobile web.
