### ISSUE TITLE
Fee schedule range value sometimes a float when API expects integer

### ISSUE THREAD

**Issue by Timo614** [big-neon/bn-web#1646]
Certain values seem to be causing the frontend to pass a floating point number to the API which leads to an error.

![Screen Shot 2019-07-23 at 1 14 28 PM](https://user-images.githubusercontent.com/1319304/61732942-c2460800-ad4c-11e9-8181-e7033ef9a927.png)
![Screen Shot 2019-07-23 at 1 14 51 PM](https://user-images.githubusercontent.com/1319304/61732943-c2460800-ad4c-11e9-8df2-3c4ad0ed88f1.png)
![Screen Shot 2019-07-23 at 1 23 14 PM](https://user-images.githubusercontent.com/1319304/61734044-2073ea80-ad4f-11e9-9bca-7b2d43ba1ffd.png)

**Comment by Timo614** [comment]
Not sure if we want to handle this here as well but I confirmed we don't cache the fee schedule value so the error messaging seen here is incorrect:
![Screen Shot 2019-07-23 at 1 16 29 PM](https://user-images.githubusercontent.com/1319304/61735322-bd378780-ad51-11e9-9f54-12bde6026a86.png)

As soon as a new order is made (since we don't update fees dynamically on an order as it would change the price prior to checkout) it immediately is reflected in even older event fees.

![Screen Shot 2019-07-23 at 1 13 52 PM](https://user-images.githubusercontent.com/1319304/61735386-dcceb000-ad51-11e9-8625-0a4db44f24ba.png)
![Screen Shot 2019-07-23 at 1 14 17 PM](https://user-images.githubusercontent.com/1319304/61735387-dcceb000-ad51-11e9-897a-074c6c4bd211.png)

![Screen Shot 2019-07-23 at 1 17 12 PM](https://user-images.githubusercontent.com/1319304/61735406-e35d2780-ad51-11e9-9e35-10519901c434.png)
![Screen Shot 2019-07-23 at 1 17 25 PM](https://user-images.githubusercontent.com/1319304/61735408-e35d2780-ad51-11e9-9951-07056f049356.png)

**Comment by Jasonvdb** [comment]
@Anziskavds can be tested by using dollar values like `0.10000002` which should just save as `0.1`

**Comment by Anziskavds** [comment]
Tested on develop and is working as expected

**Comment by Anziskavds** [comment]
Tested successful on Beta on web and mobile web.

**Comment by Anziskavds** [comment]
I don't have access on Prod to test this. I'll check tomorrow with Mike or Keith.

**Comment by Krakaw** [comment]
@Anziskavds Tested on prod successfully.

**Comment by Anziskavds** [comment]
Tested successful on Prod.
