### ISSUE TITLE
Weak Password Requirements

### ISSUE THREAD

**Issue by Krakaw** [big-neon/bn-web#173]
Weak password requirements (low risk) - the application does not require that users should have strong passwords, which makes it easier for attackers to compromise user accounts. It also allows for empty username and empty password signup. The fix could be to have a minimum password length for new sign-ups 

https://cwe.mitre.org/data/definitions/521.html
Child of big-neon/docs#28
Child of big-neon/docs#14

**Comment by Jasonvdb** [comment]
On the web I'm just validating there's an email and that email is valid. And then the password mustn't be blank. Wanted to tighten up the validation on the password but waiting to see what regex is implemented in bn-api first and then I'll pull that same logic in. Frontend validation is more just UX anyways.
