### ISSUE TITLE
Automation: Big Neon: Order Management: Test 30: ActivityItems/Refunded

### ISSUE THREAD

**Issue by mihajlokolesar** [big-neon/bn-web#1848]
**prerequisites:**
1. User should be logged in as superadmin
2. Event for given organization with purchased tickets should exits
3. Ticket for event should be refunded 
3. User should be on order management page
**steps:**
1.Refund activity item with following description should be present:[Refunder Name] refunded [refund amount] to [User Name]
2.User should click show details link to expand refunded activity item details
3.Following details should be visible:
- [Tickets]|[#order number]|Total amount of money
- [Per Ticket Fee] - Price of one ticket
- [PerUnitFees] | [order number]| amount of money
- [Per Ticket Fee] - amount of money     
4. Reason of return should be visible

**Comment by mihajlokolesar** [comment]
Hello @Tas4tari ,
This steps differs a bit from ones in testpad(order management project), I wrote the visible data as it's currently implemented. Also already mentioned in email reason of return is empty.
This is already implemented, but if some change is required please let me know. We can easily update ticket description, and test it self.

**Comment by Tas4tari** [comment]
@mihajlokolesar Will review and provide feedback

**Comment by Tas4tari** [comment]
@mihajlokolesar  Refund reason is now displaying as we have added a fix for this. This can be viewed within the Develop test environment

**Comment by mihajlokolesar** [comment]
@Tas4tari 
ok, great. thanks . I will update the test

**Comment by Tas4tari** [comment]
@Krakaw  @mihajlokolesar  Closing this issue as it has been mergeed
