### ISSUE TITLE
For staging environment change the .env names

### ISSUE THREAD

**Issue by Krakaw** [big-neon/bn-web#231]
To make a production ready docker image we may need to change the environment variable names we use, and use nginx to inject them. We can make this a function to generalize the process so that we can still use process.env vars for local development. I was thinking of using this process: https://blog.manifold.co/building-a-production-grade-container-for-your-static-javascript-application-b2b2eff83fbd

What do you think @Jasonvdb

**Comment by Jasonvdb** [comment]
Ok cool then would you mean create a settings.js file to load in all the env variables and we read them in from there throughout the app? Instead of each component referencing process.env

**Comment by Krakaw** [comment]
This is not required for the new method of staging
