### ISSUE TITLE
Implement basic date/time picker

### ISSUE THREAD

**Issue by zmelamed** [big-neon/bn-web#316]
move away from the current clock date/time pickers and use the basic implementation https://material-ui.com/demos/pickers/

**Comment by zmelamed** [comment]
Just checking in on this, I noticed the date/time picker is different now, but it seems like there is an issue when you try and set the time, clicking to the AM/PM selector, or the minute or hour selector whenever anything else is set clears what was set. Maybe an issue with onBlur or onChange handling? Let me know if you need me to explain further

**Comment by Jasonvdb** [comment]
Think I found the issue, you changed the component to use a text field but we're working with moment object throughout the project so it seems like it's some JS issue forcing an object into a string field.
https://github.com/big-neon/bn-web/commit/80157cdfbfdf2bc49c1b97eef15c5be427484248#diff-c4d339c05634ba6a2a61227280f0497b

I'll take a look at this today and try close the issue.

**Comment by zmelamed** [comment]
Ah, shoot, I thought I had stashed my change to those inputs and that what was there was something you had implemented. Sorry about the confusion. Thanks for working on it

**Comment by Jasonvdb** [comment]
@zmelamed have implemented a new date/time input mask in https://github.com/big-neon/bn-web/pull/552 . Made it compatible with the previous component and have tested. Seems fine but let me know if there any issues you notice.
