### ISSUE TITLE
Home page : Statistics > My Orders is not 0 for new user

### ISSUE THREAD

**Issue by mikethetike** [big-neon/bn-web#321]
To reproduce:
- Sign up as new user
- User is logged in 

Expected:
- "Statistics > My Orders" count should be 0

Actual:
- "Statistics > My Orders" was 2

Also, I expected the icon to be clickable and take me to those two orders

**Comment by Jasonvdb** [comment]
@mikethetike this was hardcoded as I wasn't sure if we would have an endpoint specifically for those stats. But @zmelamed seems to think we might take this out completely though as it's not that important to a user.
