### ISSUE TITLE
Date of order on Orders page needs formatting

### ISSUE THREAD

**Issue by mikethetike** [big-neon/bn-web#323]
To reproduce:
- Open /orders page

Expected
- Ordered date is in a readable format

Actual:
- Got this ugly thing: Ordered 2018-10-25T13:45:29.097901

**Comment by Jasonvdb** [comment]
That was probably an older version, design is updated:

![screenshot 2018-10-26 at 07 56 00](https://user-images.githubusercontent.com/5300488/47547149-9d735000-d8f4-11e8-8899-43294c6162f3.png)
