### ISSUE TITLE
User cannot cancel an event

### ISSUE THREAD

**Issue by SWvheerden** [big-neon/bn-web#492]
When a user cancels an event, the page just keeps loading.

**Comment by Jasonvdb** [comment]
@SWvheerden if you have problems like this please attach chrome console logs, copy/pasted or screenshots.

**Comment by Jasonvdb** [comment]
bn-api-node function name change

![screenshot 2018-12-04 at 14 43 28](https://user-images.githubusercontent.com/5300488/49442806-46a24580-f7d3-11e8-939b-e8d347f9d11d.png)
