### ISSUE TITLE
After cancelling an event in admin there is no indication the event is cancelled

### ISSUE THREAD

**Issue by philipr-za** [big-neon/bn-web#506]

**Comment by zmelamed** [comment]
connected to bigneon/bn-web#484

**Comment by Jasonvdb** [comment]
Fixing this with a pretty pink label, we can update the design later if needed. 
![screenshot 2018-12-08 at 17 32 38](https://user-images.githubusercontent.com/5300488/49687698-5d1c0a00-fb0f-11e8-95d5-4a9016b0530a.png)
