### ISSUE TITLE
After accepting an invite and creating my account I should be presented with a success modal and be dropped into the admin backend not /dashboard. Also, I had to reload the page to have the top bar and user menu in the top switch to an org member mode

### ISSUE THREAD

**Issue by zmelamed** [big-neon/bn-web#519]
[https://www.bugherd.com/projects/154576/tasks/4](https://www.bugherd.com/projects/154576/tasks/4)

**Comment by Jasonvdb** [comment]
Redirect fixed in https://github.com/big-neon/bn-web/pull/548 but still needs a success modal and a `user.refreshUser()` to load all the orgs for the top dropdown.
