### ISSUE TITLE
Org invites & Roles

### ISSUE THREAD

**Issue by zmelamed** [big-neon/bn-web#559]
requires big-neon/bn-api-node#255

- [x] As an org owner or Org Admin I should be to add people to my org by providing their email address and an access level. 
  - This should send an invite to the email address so that person can accept that invite.
  - As a user accepting an invite I should be presented with a modal to confirm that I’d like to join the org, if confirmed I should be routed to studio for that org
- [x] There should be at least the following access roles for a user. 
	1) Org Owner - Can manage team (including adding admins), view all reports, update org details, create events, manage tickets, manage holds, sell tickets through box office, check people into events
	2) Org Admin - Can manage team (cannot add other admins), view all reports, update org details, create events, manage tickets, manage holds, sell tickets through box office, check people into events
	3) Org Member -  View Events List/Dashboard, View all reports without fees, create events, manage tickets, manage holds, sell tickets through box office, check people into events
	4) Box Office -  View Events List/Event Dashboard, view orders, view tickets, view holds, sell tickets through box office, check people into events
	5) Doorperson -  View Events List, view holds, check people into events
- [x] As an org owner or Org Admin I should be able to modify an org members access level.

**Comment by Jasonvdb** [comment]
@zmelamed should roles trickle down? 
For example if someone is an org member, should they automatically get access to box office and scanning?

Or should I only allow an org member to have access to box office if they also have the `OrgBoxOffice` role?

**Comment by Jasonvdb** [comment]
As I have it now, someone has access to box office if they have the box office role or if they're an org owner / org member
