### ISSUE TITLE
Create Hold - Should have a default, or at least a drop down section of options.

### ISSUE THREAD

**Issue by zmelamed** [big-neon/bn-web#592]
[https://www.bugherd.com/projects/154576/tasks/18](https://www.bugherd.com/projects/154576/tasks/18)

**Comment by Jasonvdb** [comment]
@zmelamed is this for the auto release date field? What kind of options would you expect, can you give an example on this one?

**Comment by zmelamed** [comment]
No I think this request would be to have a drop down with the following:
“Never”
“Event Start time”
“Event Door time”
“Day of the Event (8am)”
“1 Day Before the Event (8am)”
“Custom...”
