### ISSUE TITLE
Creating ticket allocations for events

### ISSUE THREAD

**Issue by Krakaw** [big-neon/bn-web#61]
Each Ticket allocation might have the following attributes:
Name (ie. "General Admission", "VIP", "GA Early Bird")
Description
Quantity Available
Quantity Reserved
Quantity Sold
Quantity Used
Price #62 
On Sale Date/Time
Sale End Date/Time

**Comment by Jasonvdb** [comment]
@Krakaw this is related to this one https://github.com/big-neon/bn-web/issues/56 so I'll leave the events components until you're done.
I hadn't started yet but I was going to just make the UI the same as this design: https://sketch.cloud/s/dwaP2/all/promoter_events/events_create-event_add-support-artist

And then waiting on this API change to save the details so if there's any fields I missed in this issue you can add here: https://github.com/big-neon/bn-api/issues/109
