### ISSUE TITLE
Invitation email design

### ISSUE THREAD

**Issue by Krakaw** [big-neon/bn-web#637]
Child of big-neon/bigneon#37
When inviting a user to the organization the email template needs refining.

**Comment by Krakaw** [comment]
![screenshot 2018-12-17 at 09 09 43](https://user-images.githubusercontent.com/41575888/50071844-d08edd00-01db-11e9-9c5e-a872c77aad66.png)

**Comment by zmelamed** [comment]
I'll knock this out real quick
