### ISSUE TITLE
After clicking the link to accept an invitation there needs to be a sign that you are indeed accepting the invite

### ISSUE THREAD

**Issue by Krakaw** [big-neon/bn-web#639]
Child of big-neon/bigneon#37
It is not clear that you are accepting the invitation to an organization, it redirects directly to the create account page. We just need something on that page that is reminding the user that they are signing up for that organization.

**Comment by Krakaw** [comment]
You can use `bigneon.invitations.read({id: uuid})`

**Comment by Jasonvdb** [comment]
Clicking on the invite link when you're not signed up:

![screenshot 2018-12-17 at 15 01 20](https://user-images.githubusercontent.com/5300488/50088852-d9e46d80-020c-11e9-8c70-4994633ef1ba.png)

User has signed up:
![screenshot 2018-12-17 at 15 01 44](https://user-images.githubusercontent.com/5300488/50088863-dd77f480-020c-11e9-8e75-453d68e2955d.png)

User accepted:
![screenshot 2018-12-17 at 15 01 49](https://user-images.githubusercontent.com/5300488/50088882-e799f300-020c-11e9-9141-f9dedb59175f.png)

Invite expired/doesn't exist:
![screenshot 2018-12-17 at 15 01 54](https://user-images.githubusercontent.com/5300488/50088899-f1bbf180-020c-11e9-8442-15f8826aa450.png)

**Comment by Jasonvdb** [comment]
Maybe I'll just make org name and inviter name bold

**Comment by Krakaw** [comment]
Yeah, good idea, otherwise looks awesome
