### ISSUE TITLE
Footer Links - Update Footer Links

### ISSUE THREAD

**Issue by zmelamed** [big-neon/bn-web#645]
related to big-neon/bn-web#644

Update App Links per big-neon/bn-web#644
Add Privacy Policy (https://www.bigneon.com/privacy.html) and Terms (https://www.bigneon.com/terms.html) within the context of the app and update links in footer of app

Remove any other non-functioning footer links

**Comment by Jasonvdb** [comment]
"Get in touch" link can go to https://www.bigneon.com/#contact-chat
But it looks wrong with just one link so hiding it with all the others in that row.

@zmelamed  there's an array of links at the top of `./src/components/elements/footers/FooterOne.js` so feel free to uncomment ones you want to add later.

**Comment by Jasonvdb** [comment]
App store links are set by `REACT_APP_STORE_IOS` and `REACT_APP_STORE_ANDROID` in the environment
