### ISSUE TITLE
Event Creation - Errors and warnings should highlight issue inputs in real time and on save should explain each issue clearly

### ISSUE THREAD

**Issue by zmelamed** [big-neon/bn-web#704]
The use should be informed of errors proactively without blocking their actions. The field in error should highlight and a note should appear explaining the issue succinctly.
[https://www.bugherd.com/projects/154576/tasks/37](https://www.bugherd.com/projects/154576/tasks/37)

**Comment by Jasonvdb** [comment]
Related to #706

**Comment by Jasonvdb** [comment]
Expanding ticket boxes if there are any errors in the inputs
