### ISSUE TITLE
Event Creation - Ticket date/time errors should be highlighted as soon as the issue is known, not when the user tries to publish. This error prevented me from publishing, but was hidden because another ticket type was created underneath it. 

### ISSUE THREAD

**Issue by zmelamed** [big-neon/bn-web#706]
[https://www.bugherd.com/projects/154576/tasks/39](https://www.bugherd.com/projects/154576/tasks/39)

**Comment by Jasonvdb** [comment]
Unfortunately not a quick fix. Thinking of a way to handle this for all inputs to validate previous ones onblur.

**Comment by Krakaw** [comment]
Linked to #704
