### ISSUE TITLE
Event Creation - When I try to choose a date and time in the future, an error message comes up saying "duplicate record exists."  What is that referring to?

### ISSUE THREAD

**Issue by zmelamed** [big-neon/bn-web#714]
[https://www.bugherd.com/projects/154576/tasks/47](https://www.bugherd.com/projects/154576/tasks/47)

**Comment by Jasonvdb** [comment]
I tried replicating a few different ways and it all seems to work. I'm fairly certain https://github.com/big-neon/bn-web/pull/724 must have fixed this just now as well but if it happens again please reopen.
