### ISSUE TITLE
All Forms - Number Inputs should have scrolling disabled. Scrolling is less useful / prone to user error. I can erroneously scroll to negative numbers. 

### ISSUE THREAD

**Issue by zmelamed** [big-neon/bn-web#717]
[https://www.bugherd.com/projects/154576/tasks/50](https://www.bugherd.com/projects/154576/tasks/50)

**Comment by Jasonvdb** [comment]
@zmelamed I can't seem to reproduce this my side with a mouse but I'm putting in a fix that apparently disables number scrolling. If you find this still happens please reopen and I'll investigate more.
