### ISSUE TITLE
Fee Schedule - Need success/failure feedback on creation and update

### ISSUE THREAD

**Issue by zmelamed** [big-neon/bn-web#722]
[https://www.bugherd.com/projects/154576/tasks/55](https://www.bugherd.com/projects/154576/tasks/55)

**Comment by Jasonvdb** [comment]
There's a green bottom popup that says "Organization updated". And a red one that gets displayed on error. 

Change the text to:
![screenshot 2018-12-18 at 14 14 10](https://user-images.githubusercontent.com/5300488/50153490-3dcf6a80-02cf-11e9-8340-012494d23735.png)
