### ISSUE TITLE
Ticket Creation - Free tickets ($0) Should be allowed.

### ISSUE THREAD

**Issue by zmelamed** [big-neon/bn-web#723]
Free tickets should be allowed. Will need to see how this impacts validation across the purchase funnel

**Comment by Jasonvdb** [comment]
@zmelamed I can add a ticket type with a zero cost ticket price and checkout. I still need to out in credit card details to pay for the event fee though so the cart total is never zero. What was the issue you guys were getting specifically?

**Comment by Jasonvdb** [comment]
Closed in https://github.com/big-neon/bn-web/pull/617
