### ISSUE TITLE
Checkout Flow - Registration/Login modal cleanup

### ISSUE THREAD

**Issue by zmelamed** [big-neon/bn-web#744]
Need to clean up these modal designs in this flow when you login/register through the checkout flow process. For now at least updating `BigNEON` to `Big Neon` on each of the modals
![big_neon_studio](https://user-images.githubusercontent.com/456953/50173951-bde4d880-02ad-11e9-9709-9e724e20b02e.png)

**Comment by Jasonvdb** [comment]
@zmelamed this used to look a little different until I needed to comment out the facebook. 
Will just add the top icon and change the fonts.

https://share.goabstract.com/2bcfa60e-6bcf-40ab-847c-6dd9d773cb90
