### ISSUE TITLE
Reporting - Event Level - Event Summary Report

### ISSUE THREAD

**Issue by zmelamed** [big-neon/bn-web#760]
child of big-neon/docs#17
Blocked by big-neon/bn-api#809
Event Summary Report (Admins Only)
The Event Summary report shows a detailed sales summary for an event, including audit data and the information used for your settlement with Big Neon. Because this report includes revenue share, it’s only visible to users with a permission level of Org Admin.

**Comment by Krakaw** [comment]
Is this for superusers or an Org Admin (Someone below an Org Owner)
