### ISSUE TITLE
Box Office - Holds - "Joel Test" Hold showing negative price result in a negative cart total?

### ISSUE THREAD

**Issue by zmelamed** [big-neon/bn-web#769]
[https://www.bugherd.com/projects/154576/tasks/60](https://www.bugherd.com/projects/154576/tasks/60)

**Comment by Jasonvdb** [comment]
I've limited all number inputs to positive only in https://github.com/big-neon/bn-web/pull/731 so that should prevent accidents but still needs to validated in the api. @Krakaw can you transfer this to bn-api?

**Comment by Jasonvdb** [comment]
Fixed in bn-web, made a new issue for bn-api https://github.com/big-neon/bn-api/issues/793
