### ISSUE TITLE
Cannot remove ticket types from an event

### ISSUE THREAD

**Issue by Krakaw** [big-neon/bn-web#771]
Blocked by big-neon/bn-api#840
Come to think of it, this is more about choosing between externally ticketed / modifying tickets. Since these have blockchain consequences I'm just going to focus on making the split between external and what already exists as seamless as possible.

**Comment by Jasonvdb** [comment]
Ticket types are looped through and saved one at a time. So clicking on the `x` in the corner just removes it from the web and doesn't affect the API.

So would need some API endpoint to remove ticket types but ya could cause problems if tickets have already been sold. Maybe deleting a ticket type just removes it from being available for sale and doesn't actually delete it?

**Comment by Krakaw** [comment]
Agreed, we need to add a `Deleted` value to `TicketTypeStatus` enum on bn-api

**Comment by Krakaw** [comment]
Blocked by big-neon/bn-api#840
