### ISSUE TITLE
Invalid Token Errors - After leaving my browser for a long period of time, when I come back I often get Invalid token errors. Is there any logic here to refresh tokens if they're no longer valid?

### ISSUE THREAD

**Issue by zmelamed** [big-neon/bn-web#777]
[https://www.bugherd.com/projects/154576/tasks/61](https://www.bugherd.com/projects/154576/tasks/61)

**Comment by Jasonvdb** [comment]
There's an auth token valid for 15min and a refresh token used to get a new auth token. Not 100% why it works like this but I was managing it by refreshing the auth token every 5min in the background but I think a browser can pause javascript in tabs when they're not active so when you come back the token wasn't refreshing and the first api call fails. 

@Krakaw what do you think about solving this in bn-api-node? Catch 401 errors and check if the token expires, if it did then make one attempt at a refresh before attempting the API call again. Could solve the problem for the mobile app as well.

**Comment by Krakaw** [comment]
Great idea.
