### ISSUE TITLE
Drift overlaps box office checkout

### ISSUE THREAD

**Issue by Jasonvdb** [big-neon/bn-web#779]

**Comment by Jasonvdb** [comment]
@zmelamed any ideas? Should we try hide it for box office?

![screenshot 2018-12-21 at 14 47 12](https://user-images.githubusercontent.com/5300488/50343431-808f7d80-052f-11e9-89a4-6d20a8d231c1.png)

**Comment by Krakaw** [comment]
@zmelamed should we remove Drift from Box-Office and Admin pages all-together?

**Comment by Krakaw** [comment]
Dynamically adjust the parent element to move it out of the way

**Comment by zmelamed** [comment]
https://devdocs.drift.com/docs/widget-configuration#section-adding-custom-css-styles
