### ISSUE TITLE
Event Creation - Tickets - Ticket Type Sale End Date/Time Should Have Options "Event Door Time" "Event Start Time" "Event Close" "Custom..."

### ISSUE THREAD

**Issue by zmelamed** [big-neon/bn-web#790]
Ticket type Sale end date/times should have a dropdown with options 
"Event Door Time" 
"Event Start Time"
"Event Close" 
"Custom..."

Ticket Sale End date/time inputs should be hidden unless "Custom..." is selected

If "Event Door Time", "Event Start Time", "Event Close" are selected they should all remain relative to the event settings even if the event settings change.

"Event Close" should default to 5 hours following the event start for the time being.

"Event Close" Should be the default

**Comment by Jasonvdb** [comment]
@zmelamed should we allow them to set "event close" under after event date?

**Comment by zmelamed** [comment]
Yeah we will want to have event End Time. Was thinking we’d break that out into a different issue to simplify this particular task, though

**Comment by Jasonvdb** [comment]
No problem, right now I just defaulted it to start time +5 hours
