### ISSUE TITLE
Event Creation - Tickets - Sale Start Date and Sale End Date both mislabeled as "Time" and need to be laid out differently

### ISSUE THREAD

**Issue by zmelamed** [big-neon/bn-web#791]
Sale Start Date is labeled Sale Start Time
Sale End Date is labeled Sale End Time

Sale Start Date and Sale Start Time should be on the same line

Sale End Date and Sale End should be on the same line

**Comment by Jasonvdb** [comment]
@zmelamed I've placed them on one line but now it looks a little cramped. The designs only show inputs for the times but dates are also needed. Will close the issue but maybe reopen or create a new one if you think we need to change the layout to possibly split a price point into 2 lines of inputs.

![screenshot 2018-12-27 at 10 45 51](https://user-images.githubusercontent.com/5300488/50473176-9afca780-09c4-11e9-809e-247f72c1b242.png)
