### ISSUE TITLE
Event Creation - When you change the headlining artist, it should change the banner image at the top if the banner image is not user generated 

### ISSUE THREAD

**Issue by zmelamed** [big-neon/bn-web#826]
[https://www.bugherd.com/projects/154576/tasks/67](https://www.bugherd.com/projects/154576/tasks/67)

**Comment by Krakaw** [comment]
This works.

**Comment by Krakaw** [comment]
If no user is set (even if the image changed from a selected artist) overwrite the banner image when the artist changes.
