### ISSUE TITLE
Event Update - "Publish Options" for a published event should have "Published" selected displaying the date/time it was published  and 1 other option "Unpublish" Option which will change it to a draft with no publish date

### ISSUE THREAD

**Issue by zmelamed** [big-neon/bn-web#835]
[https://www.bugherd.com/projects/154576/tasks/75](https://www.bugherd.com/projects/154576/tasks/75)

**Comment by Jasonvdb** [comment]
Blocked by https://github.com/big-neon/bn-api/issues/832

**Comment by Krakaw** [comment]
@Jasonvdb Unblocked by big-neon/bn-api#833
