### ISSUE TITLE
Registration - Terms & Privacy links/agreement language

### ISSUE THREAD

**Issue by zmelamed** [big-neon/bn-web#869]
Just above the submit button on the account creation forms add in small text:
"By signing up I agree to BigNeon's terms of service & privacy policy"
"terms of service" and "privacy policy" should link to their respective pages that should open in new tabs/window

**Comment by Jasonvdb** [comment]
![screenshot 2019-01-07 at 08 35 16](https://user-images.githubusercontent.com/5300488/50752498-2f81c800-1257-11e9-9608-3dace17ac301.png)
