### ISSUE TITLE
Analytics/SEO - update meta data (at least page title) and OG data per page

### ISSUE THREAD

**Issue by zmelamed** [big-neon/bn-web#876]
Every page needs a unique title (both consumer and studio views) or we can't track how people are moving through the site effectively.
Event detail pages need unique OG data

**Comment by zmelamed** [comment]
@Jasonvdb if you want to just implement the module that will enable this and point me in the right direction for updating the meta data per page I can do this.

**Comment by Jasonvdb** [comment]
@zmelamed Busy with this in https://github.com/big-neon/bn-web/issues/894
Using react helmet to manage these tags, will have it tomorrow

**Comment by Jasonvdb** [comment]
@zmelamed https://github.com/big-neon/bn-web/pull/925 solves this for sites that can render react apps, like google and the like. Weirdly enough facebook can't render react apps so the meta data created in the app won't show up if someone shares the link on facebook.

So @sdbondi is going to work on a creative solution to that problem so keeping this issue open for him.
