### ISSUE TITLE
Invites - A user should not be required to use an exact matching email address to their invite

### ISSUE THREAD

**Issue by zmelamed** [big-neon/bn-web#880]
An invitee should not be required to use an email address that matches the email address they were invited with.

If a user is logged in display the users email address in the "Accept Invite" modal so they know what account they're accepting the invite with, "Currently logged in as: email@email.com" with a link to "Logout and Switch Account" prior to accepting the invite but don't require that they use the e-mail address they're invited with.

The admin can always delete the user from their org and re-invite if they screwed up

**Comment by Jasonvdb** [comment]
Will need a bn-api change to remove that check.
Related to https://github.com/big-neon/bn-web/issues/660

**Comment by Jasonvdb** [comment]
<img width="661" alt="screenshot 2019-01-08 at 09 13 35" src="https://user-images.githubusercontent.com/5300488/50815421-bf8e4300-1325-11e9-9b59-19ee4f02f88b.png">

**Comment by Jasonvdb** [comment]
API should be fixed when https://github.com/big-neon/bn-api/pull/850 goes in
