### ISSUE TITLE
Order Success - Text me a link section needs instructions to download apps above link field and should say "Mobile Phone Number" not "Cellphone number"

### ISSUE THREAD

**Issue by zmelamed** [big-neon/bn-web#888]
[https://www.bugherd.com/projects/154576/tasks/85](https://www.bugherd.com/projects/154576/tasks/85)
![Pasted_Image_1_7_19__2_17_PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59934f6113749d001f2f5c80/125516c66e82c728ace21e0d46d8958937878796a6e4be44a162a1ab7e79762a163bf11421d2dc18920037431f1d11f6140b1b56f6eb8c79aeb63b718d5909efd969587cc63d13a9be8b1ded09bc32975dc7e7e2de139db17770a599855d3f160f198cfb5b3da9904ecf51f04fe15f18.png)

**Comment by Jasonvdb** [comment]
@zmelamed was thinking we also need a link from this page to the user's tickets page or at least somewhere else.

**Comment by Jasonvdb** [comment]
![screenshot 2019-01-09 at 14 35 32](https://user-images.githubusercontent.com/5300488/50899795-db741080-141b-11e9-92b4-29d6ebc6ce21.png)
