### ISSUE TITLE
Event Detail Page/Checkout - Mobile web UI blocking checkout

### ISSUE THREAD

**Issue by zmelamed** [big-neon/bn-web#895]
iPhone 7 can't scroll to where I need to to select tickets:
![img_6847](https://user-images.githubusercontent.com/456953/50860226-3ccbaf00-134a-11e9-8b4f-ac6881613c92.PNG)
iPhone 7 event name cut off:
![img_6846](https://user-images.githubusercontent.com/456953/50860227-3ccbaf00-134a-11e9-9403-e8270b47b196.PNG)

**Comment by Jasonvdb** [comment]
@zmelamed for the event title at the top I'm going to adjust the font size if it's too many chars.

But for the super long descriptions even if I make it fit on mobile it doesn't look great having to scroll so far past it. I think removing it from mobile is a good idea, it does at least show on the previous screen. For desktop I can place it on the left side, not inside the ticket selection block (Similar layout to previous page).

**Comment by zmelamed** [comment]
Yeah I think removing it all together is a straightforward solution. Also keeps the call to action above the page fold which is important.
