### ISSUE TITLE
Mobile UI - Improved Modal Designs

### ISSUE THREAD

**Issue by zmelamed** [big-neon/bn-web#910]
I've had our designers add designs you can use for the modal forms that show up in mobile on boarding flows, it's merged into Master on abstract here: https://share.goabstract.com/3ff57307-e57a-4844-9fad-bee6950165c3

**Comment by Jasonvdb** [comment]
PR in to update mobile dialogs. Although scrolling still misbehaves on iOS devices: https://github.com/big-neon/bn-web/issues/953
