### ISSUE TITLE
Event Creation - Event Image should have cropping enabled and recommended value should be 2:1 ratio (reco 2160x1080px)

### ISSUE THREAD

**Issue by zmelamed** [big-neon/bn-web#917]

**Comment by zmelamed** [comment]
@Jasonvdb can you take this to the finish line? branch `917-event-images`. Looks like we need to update the upload preset setting for `gravity` to `custom` so it crops the actual image before saving it. I'm not sure where this cloudinary account is as it doesn't seem to be pointing to the one I setup.

Once you make that change image cropping should work.

We then need to make sure that everywhere throughout the app the event image is shown it maintains a 2:1 width:height ratio including the event image placeholder on the event creation form

**Comment by Jasonvdb** [comment]
@zmelamed I'm busy with displaying the images correctly with fixed aspect ratios. Might take a little while so I'm going to merge this fix for cropping in so long. Will make an extra issue for the displaying of the images.

**Comment by zmelamed** [comment]
@Jasonvdb This doesn't seem to crop the image properly.... Notice the portion of the image I select to crop vs what shows up. 
![image](https://cl.ly/d0451afb45bd/Screen%252520Recording%2525202019-01-15%252520at%25252002.38%252520PM.gif)

This should save the cropped version of the file, but it seems like it's just uploading the full file and then zooming in on it and re-positioning it. (the file that was actually uploaded is here: https://res.cloudinary.com/bigneon-dev/image/upload/v1547591886/bigneon/hcpfjsa23oal6maw2qzd.png notice it's the full image, not the cropped version).

We also need to move to the bigneon cloudinary account so we can properly QA staging images
