### ISSUE TITLE
Order Summary - Customer - All ticket fees should be combined as "Service Fees" rather than being listed as individual line items

### ISSUE THREAD

**Issue by zmelamed** [big-neon/bn-web#929]

**Comment by Jasonvdb** [comment]
@zmelamed just making sure this is what you're looking for:
<img width="1108" alt="screenshot 2019-01-14 at 11 16 26" src="https://user-images.githubusercontent.com/5300488/51104122-dd5c1c00-17ed-11e9-9269-12a83eb4fba2.png">
