### ISSUE TITLE
Force all promo images to be displayed with 1:2 aspect ratio

### ISSUE THREAD

**Issue by Jasonvdb** [big-neon/bn-web#936]

**Comment by Jasonvdb** [comment]
- [ ] Admin event creation
- [ ] Admin event list
- [ ] Landing event results
- [ ] Event view page
- [ ] Ticket selection page
- [ ] Confirmation page
- [ ] Success page

**Comment by Jasonvdb** [comment]
Fixing ratio on admin event list causes some layout issues, leaving this the way it was for now.
![screenshot 2019-01-18 at 06 49 31](https://user-images.githubusercontent.com/5300488/51366242-3af1b080-1aed-11e9-803d-36ef4166d842.png)

**Comment by Jasonvdb** [comment]
The clear image aspect ratio is maintained but the background blurry version won't work if the ratio is fixed.
![screenshot 2019-01-18 at 07 13 23](https://user-images.githubusercontent.com/5300488/51366870-96716d80-1af0-11e9-8e28-2ef95e086bd4.png)

**Comment by zmelamed** [comment]
Thanks, admin list view and background images don't need the fixed ratio for now, we'll likely improve those with a full design iteration of that list view, and background images can be skipped for now as well, I have another idea for those.
