### ISSUE TITLE
Ticket Transfer - Allow ticket transfer with user id (related to QR codes for transfers)

### ISSUE THREAD

**Issue by Krakaw** [big-neon/bn-web#959]
Blocked by big-neon/bn-api-node#297
I've set up QR codes on mobile to transfer a ticket accessing the receiving users ID.

I should be able to submit a transfer request to a user ID rather than email/phone number. If it's sent to a user ID the transfer should be instant, the receiving user should receive a push notification and email.

**Comment by zmelamed** [comment]
I actually don't believe this is needed on the web app. While we may want the ability to display the users account qr code containing json string like `{id, email, name}` with the payload for the mobile device to scan, I don't think it needs to actually be setup to accept a user id as a method of transfer as most people won't be able to access another users ID through the UI

**Comment by Jasonvdb** [comment]
Handled in  https://github.com/big-neon/bn-api/issues/964
